---
- hosts: all
  become: true
  tasks:
  - name: Pull Kubeadm images to verify connection to registry
    command: kubeadm config images pull
  - name: Initialize the Kubernetes cluster with kubeadm
    shell: kubeadm init --apiserver-advertise-address="10.0.0.10" --apiserver-cert-extra-sans="10.0.0.10" --pod-network-cidr=192.168.0.0/16
  - name: create .kube directory
    become: yes
    become_user: vagrant
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755
  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: yes
      owner: vagrant
  - name: Install Tigera Operator
    become: yes
    become_user: vagrant
    command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
  - name: Install Calico CNI
    become: yes
    become_user: vagrant
    command: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command
  - name: Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./data/join-command"
